### ISSUE TITLE
Multiple temperature/humidity sensors on a single ESP 

### ISSUE THREAD

**Issue by Heathy65** [bradsjm/hubitat-public#17]
I have 5 ESPs running esphome around my house.  Each on these is receiving temperature/humidity readings from multiple remote sensors.

When I add one of the esphome devices to C8 I select the specific temperature & humidity for one of the rooms.  This is ok.

However, how can I add the same esphome device again to select the 2nd remote sensor temperature & humidity this time?  I have tried just adding a second instance but it doesn’t work.

**Comment by bradsjm** [comment]
You would need a customized version of the driver that creates child entities, the ESPHome devices only allow a single connection so adding the driver twice will not work.
