### ISSUE TITLE
Scenes created in Tuya are loaded into Hubitat but don't run

### ISSUE THREAD

**Issue by gabrielmongefranco** [bradsjm/hubitat-public#19]
Hi, this is a follow up to my post in the Hubitat community forum. Thank you for this amazing driver! I noticed that it correctly pulled down my Tuya devices and even a scene (which I use for turning a socket off and back on to ring a doorbell). However, the On button didn't actually run the scene. I believe it's because my Home ID is too large - 9 digits long - which does not fit in an Int. But, Int shouldn't be needed since it's only used for appending to the URL in the API call anyway. 

I got it to work by changing every "Int homeId" to "String homeId", including in the triggerTuyaScene() function definition.

The only thing is that for scenes, it doesn't make a lot of sense to have a "switch" as the default component since they wouldn't have an Off function. Perhaps your code could add Tuya scenes as a push button or similar?

Regards,

Gabriel Mongefranco
Mobile Data Architect
https://gabriel.mongefranco.com

**Comment by bradsjm** [comment]
I'll change the Integer homeId to String homeId as you are right, there is no reason for it to be an Integer as its just a key.
