### ISSUE TITLE
Health check happening way more than it should

### ISSUE THREAD

**Issue by mboisson** [bradsjm/hubitat-public#23]
Hi, 
I believe this line is wrong. The second rnd number should not be there. It should be `*/${intervalMin}` instead. Is that possible ? 
https://github.com/bradsjm/hubitat-public/blob/7adbd8ea9b98268a86922491d9cc3fe489e0bd93/ThirdReality/ThirdRealityPowerMonitorPlug.groovy#L750

**Comment by bradsjm** [comment]
I think you could be right, I'll make that change but I can't test it as I'm no longer actively running Hubitat (but hope to eventually be back in a place I can)

**Comment by mboisson** [comment]
Ah, actually, I think I now know what you were trying to do. You wanted to avoid all outlets to ping in the same minute (i.e. every 00, 10, 20, 30, 40, 50, for example, if you ping every 10 minutes). 

If this is correct: 
https://stackoverflow.com/questions/12786410/run-cron-job-every-n-minutes-plus-offset

What you want is probably something like: 
```
offset = rnd.nextInt(59) % $intervalMin
``` 
and then use: 
`${offset}-59/${intervalMin}` 


which will schedule a job starting on minute `offset` which is a random number between `0` and `intervalMin`, and then runs every `intervalMin` minutes between minute `offset` and minute `59`
